"""UI helper utilities for the Streamlit app."""

from __future__ import annotations

HELP = {
    "Global seed": "Seed for reproducibility across scenario generation and policies.",
    "Horizon (steps)": "Number of discrete time steps to simulate.",
    "Rainfall type": "Choose stochastic pulses or deterministic decay profile.",
    "Baseline rainfall": "Background rainfall level for the stochastic driver.",
    "Pulse probability": "Probability of a rainfall pulse at each step.",
    "Pulse mean": "Mean intensity of rainfall pulses.",
    "Pulse std": "Standard deviation of rainfall pulse intensity.",
    "Rainfall seed (optional)": "Seed for rainfall generation; defaults to global seed.",
    "Initial intensity": "Starting rainfall intensity for deterministic decay.",
    "Decay": "Exponential decay factor for deterministic rainfall.",
    "Action max": "Maximum action intensity for all control levers.",
    "Hybrid weight (MPC)": "Weight given to MPC action in the hybrid controller.",
    "RL model path (optional)": "Path to a trained PPO model for RL-based control.",
    "Recommender horizon": "Look-ahead horizon used when scoring candidate actions.",
    "Candidate action levels (fractions of max)": "Discrete action levels to evaluate for recommendations.",
    "Weight: mortality": "Weight on deaths in the recommendation score.",
    "Weight: economic loss": "Weight on economic loss in the recommendation score.",
    "Weight: service disruption": "Weight on damage/failure in the recommendation score.",
    "Weight: action cost": "Weight on action cost penalty in the recommendation score.",
    "Cost: sanitation (u_S)": "Per-unit cost of sanitation effort.",
    "Cost: evacuation (u_E)": "Per-unit cost of evacuation effort.",
    "Cost: healthcare (u_H)": "Per-unit cost of healthcare reinforcement.",
    "Cost: personnel (u_P)": "Per-unit cost of personnel mobilization.",
    "Enable budget constraint": "Toggle budget constraint in the optimizer.",
    "Budget max": "Maximum allowable weighted sum of action costs.",
    "Budget weight: sanitation": "Budget weight for sanitation action.",
    "Budget weight: evacuation": "Budget weight for evacuation action.",
    "Budget weight: healthcare": "Budget weight for healthcare action.",
    "Budget weight: personnel": "Budget weight for personnel action.",
    "Enable safety constraints": "Toggle safety constraints in the optimizer.",
    "Max contamination": "Maximum allowable contamination under safety constraints.",
    "Max shelter pressure": "Maximum allowable shelter pressure under safety constraints.",
    "Ensembles": "Number of rainfall ensembles for stress testing.",
    "Stress test seed": "Seed for stress test rainfall generation.",
    "Pulse probability (stress)": "Pulse probability used in stress test rainfall.",
    "Pulse mean (stress)": "Pulse mean used in stress test rainfall.",
    "Pulse std (stress)": "Pulse std used in stress test rainfall.",
    "Fragility gain": "Additional penalty scaling for stress test robustness.",
    "Baseline policy": "Policy used as baseline for counterfactual analysis.",
    "Lever to increase": "Single lever to increase in counterfactual analysis.",
    "Increase (%)": "Percent increase applied to the selected lever.",
    "Counterfactual horizon": "Horizon used for counterfactual analysis.",
    "Explainability horizon": "Horizon used for sensitivity-based attribution.",
    "Enable alerting": "Toggle alerting rules.",
    "Infected threshold": "Alert threshold for infected cases.",
    "Contamination threshold": "Alert threshold for contamination.",
    "Displaced threshold": "Alert threshold for displaced population.",
    "Alert horizon": "Horizon used for alert scanning.",
    "alpha1": "Rainfall-to-depth gain in the flood model.",
    "k1": "Drainage/dissipation rate of flood depth.",
    "psi8_gain": "Damage-dependent drainage impairment factor.",
    "theta1": "Flow dissipation rate.",
    "phi1": "Flood depth to flow coupling.",
    "phi2": "Damage impact on flow.",
    "gamma8": "Flood intensity to damage rate.",
    "varphi8": "Repair effectiveness from personnel effort.",
    "kappa9": "Damage-to-failure escalation rate.",
    "rho9": "Failure recovery rate via personnel.",
    "p0": "Baseline displacement inflow.",
    "p1": "Sensitivity of displacement to flood/damage/failures.",
    "r3": "Natural resettlement rate.",
    "r3_u": "Evacuation effectiveness on reducing displacement.",
    "eta12": "Evacuation effectiveness on shelter pressure.",
    "omega0": "Flood-driven contamination source strength.",
    "beta12_c": "Shelter pressure impact on contamination.",
    "delta": "Natural contamination decay rate.",
    "sigma_p": "Sanitation effectiveness on contamination removal.",
    "beta0": "Baseline infection pressure.",
    "beta6": "Contamination-driven infection sensitivity.",
    "beta12_e": "Crowding-driven infection sensitivity.",
    "rho3": "Flood-to-exposure scaling in infection pressure.",
    "pi": "Vulnerable inflow rate.",
    "nu": "Vulnerable outflow/waning rate.",
    "gamma": "Baseline recovery rate.",
    "sigma4": "Healthcare capacity contribution to recovery.",
    "sigma4_u": "Healthcare reinforcement contribution to recovery.",
    "mu_i": "Infection fatality scaling.",
    "psi_p": "Damage/failure contribution to economic loss.",
    "c_i": "Infection contribution to economic loss.",
    "c_d": "Displacement contribution to economic loss.",
    "mu_f": "Flood-related mortality rate.",
    "mu_d": "Displacement/shelter-related mortality rate.",
    "mu_i2": "Infection-related mortality scaling.",
    "rho7": "Healthcare reinforcement rate.",
    "v7": "Failure-driven healthcare degradation rate.",
    "sigma4_x": "Outbreak pressure on healthcare capacity.",
    "rho14": "Personnel mobilization rate.",
    "k14": "Economic stress effect on personnel retention.",
    "sanitation_decay": "Decay rate of sanitation level.",
}


def help_text(label: str) -> str:
    return HELP.get(label, "")
